# Site settings
title: Toby Scales - Senior Cloud Solution Architect
description: Building Cloud Solutions for Media & Entertainment
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Toby Scales
user_description: How do you reinvent your business for the cloud?<br> Automation and iteration are the methods; business value is the goal.
user_title: Senior Cloud Architect for Media and Entertainment

# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

# Google-analytics
#google-analytics:
#  id: ""

# Exclude these files from your production _site
exclude: ['package.json', 'src' , 'node_modules', 'README.md', 'CNAME', 'Gemfile', 'Gemfile.lock', 'LICENSE']

### GH Personal Website Settings
layout: stacked
style: light

social_media:
  linkedin: tobyscales

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
     - AppSvcDemo
     - tobyscales.github.io
     - azure-bitwarden
     - Enterprise-Scale
     

